### ISSUE TITLE
ClassCastException when striking a baby zombie with a stone sword.

### ISSUE THREAD

**Issue by Zarepheth** [TheOldOne822/TheOldOne822Minecraftmods#5]
This crash happened to me last night and when I returned to the game this evening and found myself facing the same miniature zombie, it crash again - after I struck the foul creature with my stone sword.

```
java.lang.ClassCastException: net.minecraft.item.ItemAir cannot be cast to net.minecraft.item.ItemArmor
	at theoldone822.ArmorDamageRecalc.EventHandlers.HurtEvent(EventHandlers.java:42)
        ...
```

Minecraft 1.11.2
Forge 13.20.0.2255
OptiFine_1.11.2_HD_U_B7
ArmorDamageRecalc-1.11.x.jar

I have a bunch of mods loaded, so there might be some sort of conflict or interference causing the problem. Although Armor Damage Recalc is the only mod in the stack trace (I'm not counting Forge...).

Considering how long I've had this version of Armor Damage Recalc in my mods folder, I'm very surprised that it is implicated in a crash. Although, if Forge changed something that the mod depends upon, I suppose it could crash.

Log Files:

Client Latest:
[fml-client-latest.log.txt](https://github.com/TheOldOne822/TheOldOne822Minecraftmods/files/840003/fml-client-latest.log.txt)

Crash Log:
[crash-2017-03-13_20.06.50-server.txt](https://github.com/TheOldOne822/TheOldOne822Minecraftmods/files/839996/crash-2017-03-13_20.06.50-server.txt)

Server ?? Log:
[latest.log.txt](https://github.com/TheOldOne822/TheOldOne822Minecraftmods/files/840011/latest.log.txt)

**Comment by TheOldOne822** [comment]
Stupid me I put the check to prevent that crash on the line AFTER the one triggering the crash.

**Comment by Zarepheth** [comment]
Don't feel too bad; last week I spent a day and half trying to work around a problem that could be fixed by changing the case of one letter in the middle of an identifier... 
After returning to work this morning, a co-worker reviewing the situation spotted the error.
